name: strophe
description: Strophe is a Dart library for speaking XMPP via BOSH (XEP 124 and XEP 206) and WebSockets (RFC 7395).
version: 0.0.1
author: andre_developer
homepage:

dependencies:
  xml: "^3.0.0"
  http: "^0.11.3+16"
  flutter:
    sdk: flutter
    
dev_dependencies:
  test: ^0.12.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec